### ISSUE TITLE
 Mail Delivery Subsystem | Delivery Status Notification (Failure)

### ISSUE THREAD

**Issue by ghost** [j-c-peters/spending-tracker#3]
Hello! I'm having an issue simply sharing the Google Drive doc with my Google API service account. I get the following issue:

> Your message wasn't delivered to (myprojectname)@project-(myprojectname).iam.gserviceaccount.com because the domain project-(myprojectname).iam.gserviceaccount.com couldn't be found. Check for typos or unnecessary spaces and try again.

Any ideas on what could be causing this error or how to best rectify the issue? Thanks!

**Comment by peters-josh** [comment]
Make sure you enabled the [Google Sheets API](https://console.developers.google.com/apis/api/sheets.googleapis.com/overview) and then try sharing it with the Sheets workbook. Also make sure that you used the same Google account for both steps.
