### ISSUE TITLE
Trouble with sending test email from Zappier

### ISSUE THREAD

**Issue by janetvn** [j-c-peters/spending-tracker#4]
Dear Peter, 

While setting up the app on my computer, I encounter the following error at the step sending a test email to heroku app as below:

> We had trouble sending your test through.
> The app returned "Internal Server Error" with no further details. It looks like the server for your connected app is down or currently experiencing problems. Please check the app's status page or contact support if there are no reported issues.

> We made a request to spending-tracker-mai-nguyen.herokuapp.com and received (500) Internal Server Error.

May I ask what is wrong?

**Comment by peters-josh** [comment]
Did you check the Heroku logs?
